name: Mytheresa

trigger:
- none

schedules:
  - cron: "0 */2 * * *"
    displayName: "Every 2 hours"
    branches:
      include:
        - main
        
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Staging
    displayName: Staging
    variables:
      - group: 'Mytheresa-Stag' 
    jobs:
      - job: run_staging
        displayName: Run Staging
        steps:
          - template: azure-pipelines-steps.yml
            parameters:
              stage: "Staging"
              name: Staging
              script: npx playwright test
              buildId: $(Build.BuildId)

  - stage: Production
    displayName: Production
    variables:
      - group: 'Mytheresa-Prod' 
    jobs:
      - job: run_production
        displayName: Run Production
        steps:
          - template: azure-pipelines-steps.yml
            parameters:
              stage: "Production"
              name: Production
              script: npx playwright test
              buildId: $(Build.BuildId)