name: Mytheresa

trigger:
- none

schedules:
  - cron: "0 */2 * * *"
    displayName: "Every 2 hours"
    branches:
      include:
        - main
        
pool:
  vmImage: ubuntu-latest

variables:
  - group: 'Mytheresa'  

stages:
  - stage: login
    displayName: Login stage
    jobs:
      - job: run_login
        displayName: Run login
        steps:
          - template: azure-pipelines-steps.yml
            parameters:
              stage: "Login"
              name: Login
              script: npx playwright test login
              buildId: $(Build.BuildId)